cakephp/debug_kit

- src/Template/Element/cache_panel.ctp
- src/Template/Element/environment_panel.ctp
- src/Template/Element/log_panel.ctp
- src/Template/Element/sql_log_panel.ctp
- src/Template/Element/timer_panel.ctp
- src/View/Helper/ToolbarHelper.php
- tests/TestCase/View/Helper/ToolbarHelperTest.php
- webroot/css/toolbar.css
Hi guys,
I added alternative style for odd rows to improve debug tables usability.
I had to rewrite the environments and SQL log tables to avoid some CSS problems due to the DOM (no thead/tbody tags). I hope it's not a problem that I removed the use of the HTML helper to construct those tables, I think it's more readable/flexible this way and more consistant regarding the tables from the others panels.
> Alternate background color for debug tables

- webroot/js/toolbar.js
Hide ```<body>``` overflow when the toolbar is expanded (100% height) to avoid the double scrollbars (only keep the scrollbar from the iframe).
> Fix to avoid double scrollbars

- composer.json
So not strictly required now in a plugin's composer file.
Would be a good idea to let some time pass after 216 is merged, so that users still have _a_ reference to the plugin installer.
Depends on https://github.com/cakephp/app/pull/216
> Plugin installer dependency moved to cakephp/app

- src/Model/Table/RequestsTable.php
- src/Routing/Filter/DebugBarFilter.php
To combat gigantic debugkit databases, we can periodically clear out old data. There may be situations where we end up clearing out all but the most recent request, but I think that's acceptable. If a person hasn't interacted with an app in 2+ weeks, they are unlikely to remember what they last did.
> Periodically clear out old data.

- README.md
Otherwise `App::className()` can't resolve the path to the panel.
> Use dot-notation when loading plugin panels

- webroot/css/toolbar.css
In responsive design the variables tab gets lost from the toolbar when the screen is small. 
This solution is not elegant but it saves wondering "where did my tabs go" on smaller screen sizes.
Some sort of media-query driven popup or horizontal scroller would be better in the long run. Maybe that is in the works?
> Scrolling toolbar on small screen

- View/Helper/HtmlToolbarHelper.php
Without that we had totally broken pages because some keys contained mismatched HTML tags that didnt close again. Keys should also be escaped on output.
> Bugfix to avoid HTML breakage. Keys must also be h() escaped on output.

- webroot/js/js_debug_toolbar.js
Changed `js_debug_toolbar.js` `activatePanel()` to jQuery `show()`
Rationale: This makes sense because `deactivatePanel()` is using jQuery `hide()`
Justification: If you're going to use hide, you should toggle with show. -- If you aren't going to use show, you shouldn't use hide.
Discovery: This was found because on a project show/hide were over-ridden to set/remove classes vs. simply altering the display property....
> js_debug_toolbar.js activatePanel use show()

- src/Panel/VariablesPanel.php
Forms can contain validators which can contain closures. This chain breaks DebugKit. For now we'll hack around forms, but I'd like to add `__debugInfo` to Form, and Validator so we can not have specific hacks.
Refs cakephp/cakephp#6504
> Handle form instances specifically.

- src/Panel/VariablesPanel.php
f9f615c breaks the variable inspection
these lines breaks my ajax calls and gives 
```
You cannot serialize or unserialize PDO instances
```
on some variables
> remove object inspection of last commit

- src/Panel/VariablesPanel.php
Make variable dumper better. By using __debugInfo recursively we can emulate what var_dump() and debug() do under the hood. This makes the variable panel correctly handle ORM\Query, ORM\ResultSet and Form\Form instances.
> Improve variable dumper panel.

- src/DebugPanel.php
- tests/TestCase/DebugPanelTest.php
Previously the element name resolution would fail even when `$plugin = false`.
> Make it possible for non-plugin panels to work.

- src/Panel/VariablesPanel.php
- tests/TestCase/Panel/VariablesPanelTest.php
Fix the output issues related to Query and ResultSet objects. I've also added summary for the variables panel as its nice to know at a glance roughly how big of a view you might be dealing with.
> Fix variables tab not showing results for queries

- README.md
The original instructions make people to download the latest version, which is target to Cake 3.x
> Update readme to clone the right version on Cake 2.x

- src/Template/Requests/view.ctp
Adding the version as title to the panel button to quickly know the current running cakephp version, showing
CakePHP 3.0.6 Debug Kit
on hover now.
Also useful for beginners or lazy ones who quickly want to know the current version the app is running with.
> Adding the version as title to the button

- src/Panel/SqlLogPanel.php
- src/Panel/TimerPanel.php
- tests/TestCase/Panel/SqlLogPanelTest.php
- tests/TestCase/Routing/Filter/DebugBarFilterTest.php
Currently, the
Timer ( 0,25 s - 9,56 MB )
output reads as range by default. If you quickly look at it the `-` dash makes you think it is some range.
Using `/` is probably a better idea:
Timer ( 0,25 s / 9,56 MB )
Same for the SQL Log (`Sql Log ( 0 - 0 ms )`)
> Better output of timer content.

- composer.json
This avoids deprecation warnings when people use 3.1.x.
> Pin dependencies for DebugKit.

- src/Panel/VariablesPanel.php
- tests/TestCase/Panel/VariablesPanelTest.php
Simple try/catch wrapper added as a fallback for unbuffered Query objects in VariablesPanel. Fixes issue #354
> Issue #354 fix - Fallback for unbuffered queries in VariablesPanel

- composer.json
- src/Template/Element/sql_log_panel.ctp
Use a library to format SQL queries into a more readable formatting.
:notebook: This does not include syntax highlighting.
Refs #349
> Format SQL queries so they are easier to read.

- src/Cache/Engine/DebugEngine.php
- tests/TestCase/Cache/Engine/DebugEngineTest.php
This makes the DebugEngine appear as if it is not there which is nice.
Refs #359
> Make config() proxy more seamlessly.

- webroot/css/debug_toolbar.css
Some very old CSS was attempting to handle the 'no js' case, which I think is no longer a situation we should worry about. By removing these rules the tabs do not gain auto-hide/show behaviour which was the root of #367
> Remove problematic CSS that hides tabs.

- README.md
- config/bootstrap.php
- config/routes.php
This little quirk caused a bit of pain lately when I was reloading routes and debug kit wen't into an infinite XHR loop. This allows us to reload the plugin's routes after `Router::reload()` without having to reload all bootstrap setup. The only current downside I can see to loading bootstrap again when needing the routes is that the dispatcher filter is added again. But, in the future, any additional changes to bootstrap could cause problems.
This is more of an RFC I think, because it will cause "breaking" changes in existing applications, which could be more headache than it's worth. The app skel should be updated as well as the docs.
Thoughts on this?
> Moved routes to config/routes.php

- src/Controller/RequestsController.php
- src/Routing/Filter/DebugBarFilter.php
- src/Template/Layout/toolbar.ctp
- src/Template/Requests/view.ctp
- tests/TestCase/Routing/Filter/DebugBarFilterTest.php
- webroot/css/toolbar.css
- webroot/js/debug_kit.js
- webroot/js/toolbar.js
Based on the issue [#7511](https://github.com/cakephp/cakephp/issues/7511) in cakephp repo, I removed inline javascript and style code and replace them with code in separated js resp. css files.
So DebugKit is (hopefully) fully supported for Content Security Policy. DebugKit also set its own Content-Security-Policy, so it should be guaranteed that everything can be loaded by DebugKit.
> Removed inline javascript and style code to support Content Security Policy

- src/Model/Table/LazyTableTrait.php
- tests/Fixture/PanelsFixture.php
- tests/Fixture/RequestsFixture.php
- tests/TestCase/Model/Table/RequestTableTest.php
When using fixtures outside of the test harness, correctly set the active connection. This should help future proof any future connection related features that are introduced into fixtures.
Refs cakephp/cakephp#7586
> Correctly set the connection when using fixtures.

- src/Panel/IncludePanel.php
- tests/TestCase/Panel/IncludePanelTest.php
Add the total number of files included in the include panel. This makes 'fat' requests a bit more visible.
> Add summary count to Include Panel.

- src/Panel/VariablesPanel.php
- tests/TestCase/Panel/VariablesPanelTest.php
ORM\Query can emit RuntimeException when all() is called on a non-select query. Catch that error and use __debugInfo() instead.
Fixes #397
> Fix non-select queries causing debug kit to fail.

- src/Model/Entity/Panel.php
- tests/Fixture/PanelsFixture.php
postgres gets really sad when you put null bytes into character columns. With this change new schema will use binary columns which work fine in postgres.
The entity accessor makes reading small and big blobs work the same.
Refs #392
> Make panel data binary values.

- src/Controller/PanelsController.php
- src/Controller/RequestsController.php
When having an altered AppView class, the toolbar can break
> Forcing the panel to use the default cake's View class

- tests/Fixture/PanelsFixture.php
- tests/Fixture/RequestsFixture.php
Fixating the table names removes inflections which cause issues when applications apply alternate inflections.
Refs #406
> Fixate the table names of fixtures.

- tests/bootstrap.php
Tests weren't running locally without defining a host.
> Allowing sqlite tests to run locally

- src/Panel/IncludePanel.php
- src/Template/Element/include_panel.ctp
- tests/TestCase/Panel/IncludePanelTest.php
* Fix incorrectly group files on windows.
* Rename 'core' to 'cake'. I feel this name better represents what the files are. core is a bit ambiguous.
Refs #424
> Fix Include Panel on Windows.

- webroot/css/toolbar.css
Make `neat-array` display
```
-> obj1 (object)
int1  123
```
instead of 
```
-> obj1 (object)
int1  123
```
See demo
> Make neat-array display more beautiful

- webroot/css/toolbar.css
Firefox not implement break-word value but accepts break-all with similar effect
Now (without break-all) on Firefox
> Make word-break property compatible with Firefox Browser

- config/bootstrap.php
Following Cake's support of `phpdbg`, DebugKit shouldn't load in the `phpdbg` command line environment either.
> Don't load DebugKit in the phpdbg cli

- src/Panel/VariablesPanel.php
I got
>Cannot convert value to string - InvalidArgumentException
and DebugKit stopped execution completely.
Apperently it was about
```
[
(int) 0 => '5c517388-a635-41e2-bc50-b691b0d659fc'
]
```
and Cake\Database\Type\StringType->toDatabase
ROOT\Vendor\cakephp\cakephp\src\Database\Type\UuidType.php, line 39
Shouldnt DebugKit in general catch more exceptions and try to not make it impossible to continue working by rather displaying empty content than going to exception case?
Also fixed the case for another exception.
> This seems to be needed with some cases of variable content.

- src/Controller/PanelsController.php
- src/Controller/RequestsController.php
- tests/TestCase/Controller/PanelsControllerTest.php
DebugKit seemed to be inheriting our view class and layout, which in turn was loading our app's CSS and JS and breaking the toolbar (and taking a long time as it had to load a ton of stuff).
I don't have a good understanding behind the bug caused by https://github.com/cakephp/debug_kit/commit/bcf8b1a8cd2b56d32985d6759e2874ef95f89336, so I want to be sure that reverting it won't cause people's panels to break.
Pinging @markstory as you're the guy who wrote the commit 😄
> Always setting layout and class

- src/Routing/Filter/DebugBarFilter.php
- tests/TestCase/Cache/Engine/DebugEngineTest.php
- tests/TestCase/Controller/ToolbarControllerTest.php
- tests/TestCase/Database/Log/DebugLogTest.php
- tests/TestCase/Routing/Filter/DebugBarFilterTest.php
With the advent of streaming responses, some HTML responses will be streamed. DebugKit can't realistically insert itself into these streamed response bodies.
Refs #452
> Fix warnings when streaming HTML responses are used.

- webroot/js/toolbar-app.js
Safari in private browsing mode has the `localStorage` object available, but setting any item on it fails. See for example [this Stack Overflow post](http://stackoverflow.com/questions/14555347/html5-localstorage-error-with-safari-quota-exceeded-err-dom-exception-22-an).
This improved check should catch that error, thus allowing us to actually open de debug bar in Safari in a private window.
> Improve local storage check for Safari private mode

- src/Controller/PanelsController.php
PHPs unserialize issues an E_NOTICE when unserializing a class that has a private __wakeup method.
private __wakeup is useful in singletons.
Moving errors to exceptions to handle this case, seemed overkill.
The panel showed warnings for these, 
with the errors suppressed "@", 
names of the class instances still show but PHP does not issue a notice anymore.
> PHPs unserialize issues an E_NOTICE 

- webroot/js/toolbar.js
Angular 2 is using a zones library that prevents the debug kit from seeing some details about Ajax requests.
This fixes a run-time error in JS when there are no arguments.
> fix undefined error when using zones

- composer.json
- src/Routing/Filter/DebugBarFilter.php
- src/ToolbarService.php
- tests/TestCase/Routing/Filter/DebugBarFilterTest.php
- tests/TestCase/ToolbarServiceTest.php
By splitting out the core logic of the `DispatchFilter` into a separate class, we'll be able to more easily add middleware support post 3.4.0.
Once 3.4.0 is in beta I'll add the middleware.
> Prepare for middleware

- src/ToolbarService.php
- tests/TestCase/Routing/Filter/DebugBarFilterTest.php
- tests/TestCase/ToolbarServiceTest.php
Apply patch from @fquffio posted in #471 to fix tests and not break compatibility with <3.4.x. This is a much better fix than the hastily pushed bad change I made last night.
> Fix tests in 3.4.0+

- composer.json
- src/Panel/PackagesPanel.php
- src/Template/Element/packages_panel.ctp
- src/Template/Requests/view.ctp
- src/ToolbarService.php
- tests/TestCase/Panel/PackagesPanelTest.php
- tests/TestCase/Routing/Filter/DebugBarFilterTest.php
- tests/TestCase/ToolbarServiceTest.php
- webroot/css/toolbar.css
- webroot/js/debug_kit.js
This add the packages Panel as discussed  in #478 
For now it is dead simple, just parsing the `composer.lock` but I love the idea proposed by @lorenzo to get an up-to-date report or something. I will probably try to see how it can be done in the next weeks.
Is this ok to target master ?
> Add a new Packages Panel

- src/View/Helper/ToolbarHelper.php
- tests/TestCase/View/Helper/ToolbarHelperTest.php
- webroot/css/toolbar.css
`makeNeatArray` is used in Variables, Request, Session, Includes panels.
If you try to copy browser result to clipboard, text is hard to read.
When copying list to clipboard, result is
```
keyvalue1
keyvalue2
```
After the fix, clipboard contents are
```
key value1
key value2
```
> Add space between array key and value when copying 'neat array' to clipboard

- src/Panel/EnvironmentPanel.php
In Environment panel, CONFIG should be within _CakePHP Constants_ list, not _Application Constants_.
Also remove DS and ROOT from hidden constants list, as they are already in displayed list.
> Add CONFIG to CakePHP Constants list

- config/routes.php
- src/Controller/ComposerController.php
- src/Template/Element/packages_panel.ctp
- webroot/css/toolbar.css
You can check fot all outdated dependencies or choose to select only direct dependencies.
This is not ready to be merged, I'll try to find time to add tests but wanted to get feedback already.
There are places where I should add translation also if possible.
The gif screen capture is way slower than the actual behavior as it's recorded online.
> Add a tool to check composer outdated dependencies

- .gitignore
Files are created in the root directory of the project when running tests outside of an app. So easy to accidentally add them to the project.
> Ignore log files genearated by tests

- src/Template/Requests/view.ctp
- webroot/css/toolbar.css
- webroot/js/toolbar-app.js
If you have many panels, some panels may be positioned below the visible area.
This change adds scrolling capability to allow viewing these hidden panels.
> Add feature to scroll panels

- composer.json
https://thephp.cc/news/2017/02/death-star-version-constraint
> Replace death star version constraint

- tests/Fixture/RequestsFixture.php
URLs can be much larger than 255 characters.
Refs #520
> Increase length of URL column to TEXT.

- README.md
- src/Database/Log/DebugLog.php
- src/Panel/SqlLogPanel.php
- tests/TestCase/Database/Log/DebugLogTest.php
- tests/TestCase/Panel/SqlLogPanelTest.php
Disable capturing schema queries by default. This feature can be turned off by setting `DebugKit.includeSchemaReflection` to true.
Refs #539
> Ignore schema reflection queries by default.

- src/ToolbarService.php
- tests/TestCase/ToolbarServiceTest.php
Add X-DEBUGKIT-ID that was lost during the refactor to the `ToolbarService`. This header was accidentally dropped in the refactor as there were no tests ensuring it stuck around.
Refs #513
> Fix missing tracking id for history panel.

- src/Panel/RoutesPanel.php
> Don't try to load routes if router not already initialized.

- src/ToolbarService.php
- tests/TestCase/Middleware/DebugKitMiddlewareTest.php
- tests/TestCase/Routing/Filter/DebugBarFilterTest.php
- tests/TestCase/ToolbarServiceTest.php
Closes #570 
This PR adds a timestamp to the `toolbar.js` file which resolves caching issues in the browser.
I've tried to handle the edge case were the developer has copied the files locally to their webroot. What I don't do is verify if the two files are the same. I think that's a completely different issue.
> adds a timestamp to toolbar.js and updates test

- src/View/Helper/ToolbarHelper.php
- tests/TestCase/View/Helper/ToolbarHelperTest.php
I wondered that no one else ever complained about this not being usable.. :)
Without class names it is hard to work with the variables in view templates
Before:
After:
> Use proper object class names instead of just object string.

- src/Panel/IncludePanel.php
- src/Template/Element/include_panel.ctp
- tests/TestCase/Panel/IncludePanelTest.php
* Plugins were uncategorized on Windows because \ and / mismatch.
* Include panel missed many included files if they are not app/cake/plugin - add uncategorized files to 'other' group
* Many includes are from Composer vendor/ directory - add 'vendor' category and group by package
* Include panel summary displayed incorrect count, because it included count of 'Include Paths'
* Changed subgroup of app/cake/plugin to lowercase 'other' to be distinct from Controller/Model/... and to be last in list when sorted.
I've tried to add test like `$this->assertArrayHasKey('cakephp/chronos', $data['vendor']);`, but during test everything (cake/vendor/etc) is inside DebugKit directory, so everything goes into 'plugins -> DebugKit' group.
But in normal app setup, everything goes into correct categories.
> Improve Includes panel

- .travis.yml
- Model/ToolbarAccess.php
I have changed Object to Model (with useTable = false). Though I am not sure I can change the class tree in a bugfix release, direct use of CakeObject would break legacy 2.x applications.
Instead I could use `class_alias('Object', 'CakeObject')` if the `CakeObject` class was not found. But if users or some plugin's author also did it withtout class_exists() checks, those applications might break. So I thought that using Model class would be safe. But if you prefer class_alias(), I will revise my commits. Either way is fine for me if it works with PHP 7.2.
> [2.2] Fix explainQuery not working with PHP7.2 

- webroot/js/js_debug_toolbar.js
The 'Restore to current request' link on the History tab was not working. The signature should be `function (Integer index, Element element)`. Also, I removed unused variables.
> [2.2] Fix restoreCurrentState not working

- src/Controller/MailPreviewController.php
- tests/TestCase/Controller/MailPreviewControllerTest.php
- tests/test_app/Template/Email/text/test_email.ctp
Mailers will not expect the request context to be inside debugkit. Instead we should simulate the app context so that mailer links don't need `plugin => null` everywhere.
Refs #600
> Simulate app request contenxt when rendering mail previews

- src/ToolbarService.php
- tests/TestCase/ToolbarServiceTest.php
Resolves https://github.com/cakephp/debug_kit/issues/617
I didnt move the defaults up as config defaults, so it currently merges instead of overwriting.
I am also fine with overwriting and empty config array to "skip" the check if people prefer to have that option rather than using  'safeTld' config to just "add". The current approach seems "safer", though.
> Make TLD configurable.

- webroot/js/toolbar-app.js
Fixed the scroll arrows not having a data-id attribute. As it seems that when a button anywhere on the toolbar is clicked it's `data-id` attribute is passed to the ajax for loading. However the arrow buttons do not have this attribute, so `undefined` was being passed, and the resulting php from the ajax was throwing a 404.
> Resolves #625 - loadPanel receiving an undefined id

- config/bootstrap.php
- src/DebugSql.php
sql()/sqld() should accept both `Cake\ORM\Query` (`TableRegistry::get('Articles')->find()`) and `Cake\Database\Query` (`ConnectionManager::get('default')->newQuery()`)
> Accept Cake\Database\Query for sql()/sqld()

- View/Elements/environment_panel.ctp
#401 was fixed on the main branch, but I ran into the same issue on 2.2. I basically just reapplied https://github.com/cakephp/debug_kit/commit/ca07485f0497e4fcf80567c136440c0154a05cb5 on the 2.2 branch to fix it.
> Use Debugger to output constant values (on 2.2)

- config/bootstrap.php
I was looking for a while why the notice error where displayed and found that the DeprecationsPanel overwrites the set_error_handler with the default `$error_types`.
For now, I set the default value of `Configure::read` to the default value of `set_error_handler` `$error_types` argument.
> Fix that DeprecationsPanel ignores the errorLevel

- src/Database/Log/DebugLog.php
- src/Panel/SqlLogPanel.php
- tests/TestCase/Database/Log/DebugLogTest.php
Make debug_kit work again after cakephp/cakephp#13276
Not sure about the dock block. Can't find where it gets inherit from.
> Fix query DebugLog

- src/Panel/CachePanel.php
- tests/TestCase/Panel/CachePanelTest.php
If a cache configuration doesn't have a `className` we shouldn't proxy it as it is malformed.
Fixes #682
> Don't proxy invalid configuration

- src/Middleware/DebugKitMiddleware.php
Loading panels after the wrapped middleware is complete results in panels using a `shutdown` handler to collect their data to not ever be fired causing broken panels.
> Load panels before passing to the next middleware

- docs.Dockerfile
- docs/config/all.py
Update the build script for debugkit docs to also generate the 4.x docs at the same time.
> Publish 4.x docs as part of docs image.

- .travis.yml
- src/Panel/RoutesPanel.php
- src/Template/Element/routes_panel.ctp
- webroot/css/toolbar.css
Alternate solution to #553 that hides the routes but includes a toggle to show them if you want to see them. I've also updated the summary number as it shouldn't include debugkit routes which are hidden by default.
I've also made buttons a bit bigger as they were really small before.
> Hide debugkit routes with a toggle

- src/ToolbarService.php
In cake 4.0 isNew as setter is deprecated, setNew should be used.
> Fix deprecation for isNew(bool)

- src/Mailer/Transport/DebugKitTransport.php
The method got removed in https://github.com/cakephp/cakephp/pull/13536/commits/aeac7a45b675810ea10bb419f402d89bdf938ece
> Fix unknown Message::message method

- src/Model/Table/RequestsTable.php
I noticed that the size of `debug_kit.sqlite` will keep growing even though the `RequestsTable` has a garbage collection implemented. 
After some research (https://stackoverflow.com/questions/35787220/sqlite-file-size-not-decreasing-after-deleting-some-rows-from-database-in-ios and https://sqlite.org/lang_vacuum.html) I found out that disc space is not automatically freed. It is only freed if the database is recreated with the VACUUM; command.
> run VACUUM command to free disc space

- webroot/css/toolbar.css
Since the toolbar icon is placed on the right, having panels left aligned means one has to unnecessarily move the mouse towards left of screen, on highish resolutions with few panels, even to click the rightmost panel, after clicking the icon.
> Right align toolbar tabs.

- tests/bootstrap.php
Fixes:
> PHP Notice:  Constant DS already defined in /home/travis/build/cakephp/debug_kit/tests/bootstrap.php on line 25
> Fixed re-defining DS constant warning

- src/Plugin.php
Fixes https://github.com/cakephp/app/issues/770
`Plugin::middleware()` below checks `if ($this->service)`, but it was always assigned in `Plugin::bootstrap()` before CLI check.
> Skip DebugKit on CLI

- config/bootstrap.php
Using the trace_offset will allow wrapped errors to have the correct
code and context displayed.
Refs #718
Refs cakephp/cakephp#14090
> Add trace_offset to error handler

- src/Panel/MailPanel.php
In tests MailPanel can run multiple times and could potentially wrap its own wrappers. This prevents duplicate proxies from being added.
I'm not sure this will entirely fix #721 but it should help.
Refs #721
> Don't double wrap transports

- src/Model/Table/RequestsTable.php
- tests/TestCase/Model/Table/RequestTableTest.php
Revert  #704 because https://travis-ci.org/cakephp/debug_kit/jobs/639115955#L287
> Revert "Use sub query instead of ids array."

- .stickler.yml
- src/Cache/Engine/DebugEngine.php
- src/Panel/CachePanel.php
- templates/element/cache_panel.php
- tests/TestCase/Cache/Engine/DebugEngineTest.php
* Add logging to cache operations as requested in #402
* Separate clear buttons into a separate panel section.
* Refine miss stats so they are more clear about only be related to get.
* Add logging for the engine, operation, key and duration of each
operation. This removes caching from the timer panel, but I see that
as an improvement as caching in the timing waterfall mostly added
noise.
> Improve Cache Panel

- .travis.yml
Update php versions and remove php 7.4 failure. Update test db names to match cakephp.
> Update travis config to match cakephp

- src/Panel/TimerPanel.php
I messed up removing one of the translation calls. Fixed in back-port as well.
> Fixed typo in DebugTimer call

- src/Model/Table/RequestsTable.php
Time based GC might sometimes to fail if requests are periodical (ex. every 2 seconds at odd seconds, so never on 100th second) or many requests in short burst, and database might grow quickly.
Simple random number might be more stable to trigger GC.
I'm thinking too if probability could depend on value of `DebugKit.requestCount` as it grew to 100 stored requests on average while only last 20 are used.
> Use rand() to trigger garbage collection

- src/Model/Table/RequestsTable.php
- src/ToolbarService.php
- tests/TestCase/ToolbarServiceTest.php
Fixes https://github.com/cakephp/debug_kit/issues/759
We should allow concurrent requests without throwing fatal exceptions.
> Allow saving requests to fail gracefully

- composer.json
- templates/element/environment_panel.php
`Debugger::exportVar()` how emits escaped HTML in 4.1
Fixes #766
> Remove double escaping in templates

- src/ToolbarService.php
- tests/TestCase/ToolbarServiceTest.php
While learning CakePHP, I could not get the DebugKit toolbar to appear on my server with private address 172.18.0.52. After looking around in the DebugKit code, I noticed that the private class B IPv4 range (172.16.0.0 - 172.31.255.255) is missing from the `isSuspiciouslyProduction()` method, so DebugKit thinks that 172.18.0.52 is a public address. Of course I could set `forceEnable` to `true`, to force the toolbar to appear, but that should not be necessary.
I can not simply add "172" to the array of private octects either, because there is a phpunit testcase for public address 172.112.34.2, which would then fail. The current code bases its judgement whether an IP address is public or private, only on the first octet of an IP address. As a result, it assumes (for example) that 192.1.2.3 …
> Allow 172.16.0.0/12 and IPv6 private ranges

- src/Cache/Engine/DebugEngine.php
> fix: pass default-param to underlying cache-engine

- src/Model/Table/LazyTableTrait.php
Refs https://github.com/cakephp/debug_kit/issues/797
This doesn't fix the issue reported, but it fixes the check that should thrown an exception when this happens.
We don't seem to have unit tests for loading the fixtures.
> Fix exception when fixture class isn't found

- docs/en/index.rst
- tests/Fixture/PanelsFixture.php
- tests/Fixture/RequestsFixture.php
This fixes the authoritative autoloader generation which bakes class names into the autoloader lookup.
Fixes #797
> Fix authoritative autoloader compatibility.

- src/Panel/CachePanel.php
- tests/TestCase/Panel/CachePanelTest.php
Don't overwrite the entire cache configuration data. This allows
`Cache::getConfig()` to continue working as it normally should.
Fixes #801
> Preserve cache configuration better.

- tests/TestCase/Panel/DeprecationsPanelTest.php
Refs https://github.com/cakephp/debug_kit/issues/795
We were hiding php errors and warnings in tests after DeprecationsPanelTest.
> Fix DeprecationsPanelTest hiding php errors

- psalm-baseline.xml
- psalm.xml
- src/Cache/Engine/DebugEngine.php
- src/Model/Entity/Panel.php
- src/ToolbarService.php
- tests/TestCase/Panel/SqlLogPanelTest.php
- tests/TestCase/ToolbarServiceTest.php
- tests/TestCase/View/Helper/ToolbarHelperTest.php
When the host application doesn't have SQLite installed failing to save the toolbar data should not cause the page to 500. Instead we can log the error and not end up showing the toolbar iframe as there is not Request persisted.
Refs cakephp/cakephp#15492
> Fix failure when debug_kit connection does not exist 

- config/routes.php
- src/Controller/PanelsController.php
- src/Model/Entity/Panel.php
- src/Model/Table/PanelsTable.php
- src/ToolbarService.php
- templates/element/history_panel.php
- tests/TestCase/Controller/PanelsControllerTest.php
- tests/TestCase/ToolbarServiceTest.php
Closes #834
With the added Reload button, the "back to current request" will never be the same. Should I add some logic to keep the request id ?
Also, any hint about how should I test this will be appreciated
> Show Toolbar on Dashboard - Reload Request History
