- src/Panel/VariablesPanel.php
- src/View/Helper/ToolbarHelper.php
I think this won't be fix in phpcs...
> 3.0 fix cs

- src/Model/Table/PanelsTable.php
- src/Model/Table/RequestsTable.php
- tests/Fixture/PanelsFixture.php
- tests/TestCase/Model/Table/RequestTableTest.php
- tests/bootstrap.php
Having a foreign key is a good idea, and will help MySQL delete rows more efficiently.
Refs #309
> Add foreign keys to PanelsFixture.

- composer.json
> Suggest people use sqlite.

- composer.json
> dev-master should be aliased to 3.0.x-dev, not 2.2.x-dev

- View/Elements/sql_log_panel.ctp
- webroot/css/debug_toolbar.css
A small improvement when trying to find duplicate queries, they will be marked in red.
See img:
> 2.2 duplicate queries

- src/View/Helper/ToolbarHelper.php
https://github.com/cakephp/debug_kit/pull/326 For 3.x
> Escape key

- View/Helper/ToolbarHelper.php
this is happening in some cases on my site.
```
Error [8]: Undefined index: query [195]: APP/Plugin/DebugKit/View/Helper/ToolbarHelper.php
```
Backtrace (seems to be an error page / after exception render)
```
ToolbarHelper::getQueryLogs(): APP/Plugin/DebugKit/View/Helper/ToolbarHelper.php:195
include: APP/Plugin/DebugKit/View/Elements/sql_log_panel.ctp:33
View::_evaluate(): APP/Vendor/cakephp/cakephp/lib/Cake/View/View.php:961
View::_render(): APP/Vendor/cakephp/cakephp/lib/Cake/View/View.php:923
View::_renderElement(): APP/Vendor/cakephp/cakephp/lib/Cake/View/View.php:1217
View::element(): APP/Vendor/cakephp/cakephp/lib/Cake/View/View.php:418
include: APP/Plugin/DebugKit/View/Elements/debug_toolbar.ctp:45
View::_evaluate(): APP/Vendor/cakephp/cakephp/lib/Cake/View/View.php:961 …
```
> fix undefined index error

- .travis.yml
and remove deprecated option --dev for composer
> add php7 build

- src/Controller/PanelsController.php
- src/Controller/RequestsController.php
to be merged after cakephp/cakephp#7223
> replace `getView()` by the new `viewBuider()`

- src/Model/Table/RequestsTable.php
The table definitions have constraints between requests and panels. Clearing the requests table first will violate those constraints.
Refs cakephp/docs#3163
> Clear tables in the correct order.

- composer.json
Related to https://github.com/cakephp/cakephp/pull/7449
> Add cakephp/cakephp-codesniffer as dev dependency

- README.md
> Add link to 2.2 branch

- README.md
> Add link to Composer

- README.md
> Add link to "Loading a Plugin" section of the book

- src/Model/Table/RequestsTable.php
> Only keep the last x amount of requests

- src/Panel/IncludePanel.php
Cake 3 has more top level packages
> Adding more file types to the Include panel

- src/Controller/PanelsController.php
- src/Template/Requests/view.ctp
- tests/TestCase/View/Helper/SimpleGraphHelperTest.php
- tests/TestCase/View/Helper/ToolbarHelperTest.php
- webroot/js/debug_kit.js
- webroot/js/toolbar-app.js
The history panel was relying on the recently fixed RequestHandler bug, and sorting has been broken for a while.
> Fix history loading and sorting issues

- webroot/css/toolbar.css
Fixes a scrollbar issue that appears on chrome
http://i.imgur.com/rkwkUxT.gif
> scrollbar fix

- composer.json
Refs https://github.com/cakephp/bake/issues/268
> Add missing direct dependency

- webroot/js/debug_kit.js
- webroot/js/toolbar-app.js
- webroot/js/toolbar.js
This should help make stickler less whiny for future pull requests.
Refs #455
> Fix JSCS errors.

- src/Panel/RoutesPanel.php
- src/Routing/Filter/DebugBarFilter.php
- src/Template/Element/routes_panel.ctp
- tests/TestCase/Panel/RoutesPanelTest.php
- tests/TestCase/Routing/Filter/DebugBarFilterTest.php
- webroot/css/toolbar.css
> Routes panel

- src/Template/Requests/view.ctp
- webroot/css/toolbar.css
- webroot/js/debug_kit.js
sorry the gif quality is pretty bad but don't want to spend time on this 😢
> Add CakePHP version directly in the toolbar

- .travis.yml
- composer.json
Dont use the broken global one
Fixes at least the 5.6 fails.
> Fix phpunit issue

- src/Mailer/MailPreview.php
> Added the ModelAwareTrait to MailerPreview

- src/Mailer/Transport/DebugKitTransport.php
- tests/TestCase/Model/Table/RequestTableTest.php
- tests/TestCase/ToolbarServiceTest.php
- tests/bootstrap.php
> Remove blank lines and fix doc block

- src/Controller/MailPreviewController.php
- src/Template/MailPreview/email.ctp
- tests/TestCase/Controller/MailPreviewControllerTest.php
- tests/bootstrap.php
- tests/test_app/Plugin/DebugkitTestPlugin/src/Mailer/Preview/TestMailerPreview.php
- tests/test_app/Plugin/DebugkitTestPlugin/src/Mailer/TestMailer.php
Otherwise mail previews from plugins would not be found.
Fixes #501
> Pass plugin to the iframe for rendering mail messages.

- src/Controller/ComposerController.php
> Avoid undefined variable

- composer.json
- tests/Fixture/PanelsFixture.php
Try to avoid truncation issues for more folks.
Refs #512
> Make content column a longblob.

- composer.json
It's more consistent.
https://getcomposer.org/doc/articles/versions.md#caret
https://blog.madewithlove.be/post/tilde-and-caret-constraints/
> Use caret operator where sensible

- src/ToolbarService.php
- tests/TestCase/ToolbarServiceTest.php
Don't try to modify read only streams like file responses.
Refs #528
> Fix errors on non-writable streams.

- composer.json
- src/Controller/MailPreviewController.php
- src/Model/Table/LazyTableTrait.php
- tests/TestCase/Controller/MailPreviewControllerTest.php
- tests/TestCase/Controller/PanelsControllerTest.php
> Fix undefined variable error in mail preview

- src/Mailer/PreviewResult.php
- tests/TestCase/Controller/MailPreviewControllerTest.php
- tests/test_app/Template/Email/text/test_email.ctp
- tests/test_app/Template/Layout/Email/text/default.ctp
> Fix empty email previews (#541)

- .travis.yml
- src/Template/Requests/view.ctp
"DIV" is not allowed as direct child of "UL".
> Generate valid HTML.

- README.md
Be clearer on what debugkit does and where you should use it.
> Update readme to be explicit on what debug kit

- config/routes.php
- webroot/js/toolbar-app.js
- webroot/js/toolbar.js
Resolves https://github.com/cakephp/debug_kit/issues/551
> Use 3.1+ dashed route scheme for URLs.

- src/Panel/IncludePanel.php
At the moment you get on windows something like `CAKE/Datasource\ConnectionManager.php`
> Use  DIRECTORY_SEPARATOR for file path

- .gitignore
Adds the following to the `.gitignore` file:
```
.idea/*
nbproject/*
.vscode
```
> ignores the common IDE files

- webroot/js/toolbar-app.js
> Only call indexOf on strings.

- src/Template/Element/packages_panel.ctp
- src/Template/Layout/toolbar.ctp
- src/Template/Requests/view.ctp
Refs: https://github.com/cakephp/cakephp/issues/11717
> prevent to use app base url

- src/Panel/EnvironmentPanel.php
- src/Template/Element/environment_panel.ctp
- tests/TestCase/Panel/EnvironmentPanelTest.php
https://github.com/cakephp/debug_kit/issues/533
> add ini environment

- src/Controller/Component/ToolbarComponent.php
- src/Controller/ComposerController.php
- src/Controller/MailPreviewController.php
- src/Controller/ToolbarController.php
- src/Model/Table/PanelsTable.php
- src/Panel/PanelRegistry.php
- src/Panel/VariablesPanel.php
- src/Shell/WhitespaceShell.php
- src/Template/Element/cache_panel.ctp
- src/Template/Element/environment_panel.ctp
- src/Template/Element/include_panel.ctp
- src/Template/Element/mail_panel.ctp
- src/Template/Element/packages_panel.ctp
- src/Template/Element/request_panel.ctp
- src/Template/Element/sql_log_panel.ctp
- src/Template/Element/variables_panel.ctp
- src/Template/Layout/mailer.ctp
- src/Template/MailPreview/email.ctp
- src/Template/MailPreview/index.ctp
Some strings do not have a function, so it was added.
> Put I18n to some strings

- src/Template/Element/cache_panel.ctp
- src/Template/Element/mail_panel.ctp
- src/Template/Element/packages_panel.ctp
> fix for #582

- README.md
follow main repo.
see https://github.com/cakephp/debug_kit/tree/dereuromark-patch-1 readme
> Add missing badges.

- src/Plugin.php
Support new plugin collection.
> Add Plugin class.

- README.md
> Update requirements in README.md

- src/Controller/Component/ToolbarComponent.php
The message didn't mention the need to load the routing
> Includes routes enabling

- src/ToolbarService.php
> Add logging when debugkit turns itself off.

- src/Panel/CachePanel.php
- tests/TestCase/Panel/CachePanelTest.php
> Fix notice error on incomplete cache configuration.

- config/bootstrap.php
- src/Controller/MailPreviewController.php
- src/DebugInclude.php
- src/Panel/DeprecationsPanel.php
- src/Panel/IncludePanel.php
- src/ToolbarService.php
> Fix duplicate class names caused by `DebugKit\Plugin` existing.

- src/Controller/MailPreviewController.php
- src/Panel/PanelRegistry.php
Fix class name is not placed in error message
> Fix variables in translation with quotes

- src/ToolbarService.php
- tests/TestCase/ToolbarServiceTest.php
It's now a publicly available TLD.
> Don't treat "dev" as a safe TLD by default.

- webroot/js/toolbar.js
Fixes #663
- Added listeners
- Added check if llisteners already applied
> Added turbolinks compatibility

- src/Mailer/PreviewResult.php
- src/Plugin.php
- tests/TestCase/Controller/MailPreviewControllerTest.php
We were using recently broken APIs. Update to the new Mailer/Message interface
> Fix email rendering.

- src/Panel/PanelRegistry.php
Small fix to make debug_kit compatible to the latest changes in the core.
> Add missing type hints

- src/Middleware/DebugKitMiddleware.php
> Don't try to enable panels if service is disabled.

- src/Controller/ComposerController.php
Countary to any sane person's expectations in php (bool)"false"
does not evaluate to "false" but "true" instead
> Fix string to bool conversion

- src/Model/Table/LazyTableTrait.php
> Improve error message when sqlite file could not be created.

- src/Controller/ComposerController.php
- tests/TestCase/Controller/ComposerControllerTest.php
Add some coverage to the composer controller.
> Add tests for composer controller and fix deprecation.

- src/Template/Element/cache_panel.ctp
- src/Template/Element/packages_panel.ctp
> add csrf to ajax headers

- src/Controller/MailPreviewController.php
> Update App::path() usages

- .travis.yml
- phpunit.xml.dist
- src/Panel/RequestPanel.php
- src/Panel/RoutesPanel.php
- tests/TestCase/Cache/Engine/DebugEngineTest.php
- tests/TestCase/Controller/ToolbarControllerTest.php
- tests/TestCase/Database/Log/DebugLogTest.php
- tests/TestCase/DebugTimerTest.php
- tests/TestCase/Middleware/DebugKitMiddlewareTest.php
- tests/TestCase/Model/Table/RequestTableTest.php
- tests/TestCase/Panel/DeprecationsPanelTest.php
- tests/TestCase/Panel/LogPanelTest.php
- tests/TestCase/Panel/RoutesPanelTest.php
- tests/TestCase/Routing/Filter/DebugBarFilterTest.php
- tests/TestCase/ToolbarServiceTest.php
refs https://github.com/cakephp/debug_kit/issues/708
> Fix up return types, better asserts and PHP74

- composer.json
- src/Command/BenchmarkCommand.php
> Update chronos constraint

- .travis.yml
- composer.json
- src/Controller/DashboardController.php
- src/View/Helper/ToolbarHelper.php
- tests/TestCase/Controller/DashboardControllerTest.php
Updated php 7.4 config.
Added phpcs to CHECKS run.  Removed references to php 7.1.
> Align travis config with cakephp

- src/Command/BenchmarkCommand.php
- src/View/Helper/SimpleGraphHelper.php
- tests/TestCase/DebugSqlTest.php
- tests/TestCase/Panel/VariablesPanelTest.php
- tests/TestCase/ToolbarServiceTest.php
> Port fixes from #716 to master

- composer.json
- docs/en/index.rst
- docs/fr/index.rst
- src/Controller/ComposerController.php
- src/Controller/DashboardController.php
- src/Controller/DebugKitController.php
- src/Controller/MailPreviewController.php
- src/Controller/PanelsController.php
- src/Controller/RequestsController.php
- src/Controller/ToolbarController.php
- tests/TestCase/Controller/DebugKitControllerTest.php
- tests/bootstrap.php
Add configuration option to skip authorization for DebugKit requests.
Port #734 to 4.x
> DebugKitController beforeFilter check if debug is enabled

- src/Panel/RoutesPanel.php
- src/Panel/VariablesPanel.php
Forward port https://github.com/cakephp/debug_kit/pull/743
> Cleanup docblocks.

- composer.json
Resolves https://github.com/cakephp/debug_kit/issues/747
> Remove unneeded dependency

- src/Panel/TimerPanel.php
Fixes https://github.com/cakephp/debug_kit/issues/746
> Updated timer panel prefixes

- src/Panel/TimerPanel.php
https://github.com/cakephp/debug_kit/pull/750
> Back-port #750 to 3.x

- src/Model/Table/RequestsTable.php
https://github.com/cakephp/debug_kit/pull/756
> Port - Use rand() to trigger garbage collection

- docs/en/index.rst
- src/ToolbarService.php
- tests/TestCase/ToolbarServiceTest.php
> Allow ignoring paths.

- .github/workflows/ci.yml
- composer.json
- phpunit.xml.dist
- src/Command/BenchmarkCommand.php
- tests/Fixture/PanelsFixture.php
- tests/Fixture/RequestsFixture.php
- tests/TestCase/Controller/DashboardControllerTest.php
- tests/TestCase/Controller/MailPreviewControllerTest.php
- tests/TestCase/Controller/PanelsControllerTest.php
- tests/TestCase/Controller/RequestsControllerTest.php
- tests/TestCase/Controller/ToolbarControllerTest.php
- tests/TestCase/FixtureFactoryTrait.php
- tests/bootstrap.php
- tests/test_app/Form/TestForm.php
Convert what we had in travis to GitHub Actions
> Add Github Actions based CI

- src/Plugin.php
This code isn't part of a unit test.
> Run default error handler if none set

- composer.json
- psalm-baseline.xml
- src/Panel/VariablesPanel.php
- src/View/Helper/ToolbarHelper.php
- templates/element/variables_panel.php
- tests/TestCase/Panel/VariablesPanelTest.php
- tests/TestCase/View/Helper/ToolbarHelperTest.php
Use the new Debugger features to generate a more complete dataset for
the Variables Panel. The new data will include hidden properties and
not mangle Entity data.
Fixes #795
Fixes #659
Fixes #277
> Improve variables panel

- webroot/css/toolbar.css
> Fix monospace font family
